repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.74.1
      hooks:
        - id: terraform_docs
          description: Generates documentation for Terraform modules.
          args:
            - --args=--config=hooks/.terraform-docs.yml
            - --hook-config=--create-file-if-not-exist=true
        - id: terraform_tflint
          description: Validates all Terraform configuration files with TFLint.   
          args:
            - --args=--config=__GIT_WORKING_DIR__/hooks/.tflint.hcl
        - id: terraform_fmt
          description: Rewrites all Terraform configuration files to a standard format.
          args:
            - --args=-diff
            - --args=-recursive=true
        - id: terraform_validate
          description: Verifies the code syntax and structure.
